# Generated by Django 5.1.5 on 2025-01-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_tecnonacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
