# Generated by Django 5.1.5 on 2025-02-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_tecnonacho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('faltantes', 'Faltantes'), ('demasiadas_existencias', 'Demasiadas existencias'), ('bajo_pedido', 'Bajo pedido')], default='faltantes', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
