# Generated by Django 5.1.5 on 2025-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_tecnonacho', '0002_alter_producto_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
