# Generated by Django 5.1.5 on 2025-02-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_tecnonacho', '0003_alter_producto_categoria_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('faltantes', 'Faltantes'), ('demasiadas_existencias', 'Demasiadas existencias'), ('bajo_pedido', 'Bajo pedido'), ('realizados', 'Realizados'), ('agotados', 'Agotados con el proveedor')], default='faltantes', max_length=25),
        ),
    ]
