# Generated by Django 5.1.5 on 2025-02-17 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_tecnonacho', '0006_producto_modificado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_origen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modificado_por',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
